[project]
name = "segmentanything3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "imageio>=2.36.0",
    "open3d>=0.18.0",
    "opencv-python>=4.10.0.84",
    "pointops",
    "scikit-image>=0.24.0",
    "segment-anything",
    "torch>=2.4.0",
    "torchaudio>=2.4.0",
    "torchvision>=0.19.0",
]

[tool.uv]
python-preference = "only-system"
dev-dependencies = [
    "black>=24.8.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "poethepoet>=0.28.0",
    "pyright==1.1.379",
    "pytest>=8.3.2",
]

[tool.uv.pip]
system = true
no-build-isolation-package = ["pointops"]

[tool.uv.sources]
segment-anything = { git = "https://github.com/facebookresearch/segment-anything.git" }
pointops = { path = "libs/pointops" }
